### ISSUE TITLE
i get this error can u help me? ->  Member "toString" not unique after argument-dependent lookup in type(library Strings).

### ISSUE THREAD

**Issue by damasb** [dtbuchholz/tutorial-chainlink-dynamic-nft#1]
TypeError: Member "toString" not unique after argument-dependent lookup in type(library Strings).
   --> contracts/dynNFT.sol:139:21:
    |
139 |                     Strings.toString(0) // Value of `seed` is at `stage_id` `0`
    |                     ^^^^^^^^^^^^^^^^

Error HH600: Compilation failed

**Comment by dtbuchholz** [comment]
@damasb oops, missed this, sorry for the delay! i'll push an update to this repo next week.

the issue stems from OpenZeppelin's API change, which requires you to instantiate the variable first before you use the `toStrings` method. it's an annoying change imo, but if you don't do something like the following, the compiler doesn't know if `toStrings` is referencing an unsigned or signed integer. before, it just assumed the integer was unsigned.

```solidity
uint256 seedStage = 0;
TablelandDeployments.get().mutate(
    address(this),
    _tokensTableId,
    SQLHelpers.toInsert(
        _TOKENS_TABLE_PREFIX,
        _tokensTableId,
        "id," // Token ID column
        "stage_id", // Flower stage column (i.e., it starts as a seed and then grows)
        // Data to insert -- the `tokenId` and `stage` as comma separated values
        string.concat(
            Strings.toString(tokenId),
            ",",
            Strings.toString(seedStage) // Value of `seed` is at `stage_id` `0`
        )
    )
);
```

**Comment by dtbuchholz** [comment]
Fixed with the latest updates
